version: "3"

services:
  db:
    image: postgres:latest
    volumes:
      - data:/var/lib/postgresql/data
    env_file: ./.env.local #Here we are using the already existing .env.local file
    ports:
      - "54321:5432"
    networks:
      - blitz-coffee

  redis:
    depends_on:
      - db
    image: "bitnami/redis:latest"
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - blitz-coffee

volumes:
  data:
networks:
  blitz-coffee:
    driver: bridge
